name: CI
on: [push, pull_request]

jobs:
  BuildPDF:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install LaTex
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-science texlive-bibtex-extra biber latexmk

      - name: Compile LaTex document
        run: |
          source .envrc
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "TEXMFHOME: $TEXMFHOME"
          echo "TEXINPUTS: $TEXINPUTS"
          make all
