name: CI
on: [push, pull_request]

jobs:
  BuildPDF:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install LaTex
        run: |
          sudo apt-get install --no-install-recommends texlive-latex-base texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-science texlive-bibtex-extra biber latexmk

      - name: Copy texmf
        run: cp -r texmf "$HOME"

      - name: Setup environment variable
        run: |
          source "$GITHUB_WORKSPACE/.envrc"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "TEXMFHOME: $TEXMFHOME"
          echo "TENINPUTS: $TEXINPUTS"
          echo "TEXMFHOME=$TEXMFHOME" >> $GITHUB_ENV

      - name: Log TEXMFHOME through kpsewhich
        run: kpsewhich -var-value TEXMFHOME

      - name: Log TEXINPUTS through kpsewhich
        run: kpsewhich -var-value TEXINPUTS

      - name: Compile LaTex document
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "TEXMFHOME: $TEXMFHOME"
          echo "TEXINPUTS: $TEXINPUTS"
          make all
